apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: frontend
        image: docker.io/agranov9/frontend-todo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_URL
          value: "10.109.233.239:8000/todo/"
