apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: frontend
        image: agranov9/frontend-todo:latest
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_URL
          value: "http://10.105.170.137:8000"
