apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: green
  ports:
    port: 5137
    protocol: TCP
    targetPort: 5173
    
